version: "3.8"

services:
  app:
    build:
      target: ${TARGET:-dev}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
